# Mandatory
server:
  port: 5003

# Mandatory.
cache:
  host: "redis_db"
  port: 6379
  ttl: "PT10M"
  # Optional. Default is 0.
  db: 1

# Optional.
responseCache:
  mongoURL: "mongodb://mongo_db:27017/ps"
  ttl: "PT10M"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
  synchronous: 
    mongoURL: "mongodb://mongo_db:27017/ps"

  #webhook:
  #  url: "https://beckn.free.beeceptor.com/clientURL"
  
  #messageQueue: 
  #  amqpURL: "amqp://guest:guest@localhost:5672"
  #  incomingQueue: "protocol-server-incoming"
  #  outgoingQueue: "protocol-server-outgoing"

# Mandatory.
app:
  # Mandatory.
  mode: bap

  # Two types of gateway mode present.
  # client and network.
  gateway:
    mode: client
    inboxQueue: "inbox"
    outboxQueue: "outbox"
    amqpURL: "amqp://guest:guest@queue_service:5672"

  # Mandatory.
  actions:
    requests:
      search:
        ttl : "PT10S"
      init:
        ttl : "PT10S"
      select:
        ttl : "PT10S"
      confirm:
        ttl : "PT10S"
      status:
        ttl: "PT10S"
      update:
        ttl: "PT10S"
      track:
        ttl: "PT10S"
      
    
    responses: 
      on_search:
        ttl: "PT10S"
      on_init:
        ttl: "PT10S"
      on_select:
        ttl: "PT10S"
      on_confirm:
        ttl: "PT10S"
      on_status:
        ttl: "PT10S"
      on_update:
        ttl: "PT10S"
      on_track:
        ttl: "PT10S"
  
  # Mandatory.
  privateKey: "NtNBr1rjJ0cXBqxwhbqNOzWB5SeQynKPssIqAWLlRS5GfL7nVZat4ofek/jJTLoeO177h49vDL55nG2k250Lgg=="
  publicKey: "Rny+51WWreKH3pP4yUy6Hjte+4ePbwy+eZxtpNudC4I="

  # Mandatory.
  subscriberId: "YASH-local-PS-BAP"
  subscriberUri: "http://localhost:5002"
  
  # Mandatory.
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: false
  uniqueKey: "Yash-local-PS-BAP"
  
  # Mandatory.
  city: "std:080"
  country: "IND"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: "PT3S"
  httpRetryCount: 2